### ISSUE TITLE
アカウント新規登録の作成

### ISSUE THREAD

**Issue by takanori-matsushita** [CODEBASE-Okinawa/codebase_books_nobotsun#1]
Notion
https://www.notion.so/codebase098/ce74e531a4424763b85e93638e0c7462?v=36964af226a44492a02f68f26e013a93&p=5cfaf205d3c341928fd6487ff991551e&pm=s

- [x] APIの実装
- [x] デザインの実装
- [x] react-fook-formの追加

**Comment by Hitoshi-Noborikawa** [comment]
使うライブラリ
・https://next-auth.js.org/
・フォームには[react-fook-form](https://react-hook-form.com/)を使用する


・メールとpassword認証

**Comment by Hitoshi-Noborikawa** [comment]
import { hash } from 'bcryptjs' すると module not found になる。

**Comment by Hitoshi-Noborikawa** [comment]
bcryptjsはエラー解決に時間がかかりそうなので、crypto-hashにしました。
