### ISSUE TITLE
本詳細の作成

### ISSUE THREAD

**Issue by takanori-matsushita** [CODEBASE-Okinawa/codebase_books_nobotsun#4]
Notion
https://www.notion.so/codebase098/ce74e531a4424763b85e93638e0c7462?v=36964af226a44492a02f68f26e013a93&p=f54b60f8badf44be81f1439301947e9e&pm=s

- [x] デザインの実装
- [x] APIの実装

**Comment by Hitoshi-Noborikawa** [comment]
作成しました。
