### ISSUE TITLE
本を借りるページの作成

### ISSUE THREAD

**Issue by takanori-matsushita** [CODEBASE-Okinawa/codebase_books_nobotsun#5]
Notion
https://www.notion.so/codebase098/ce74e531a4424763b85e93638e0c7462?v=36964af226a44492a02f68f26e013a93&p=3e8c937bc9504e9f917146fd54cf436a&pm=s

- [x] デザインの作成
- [x] APIの実装
- [x] 本を借りる際の画面の動きを実装

**Comment by Hitoshi-Noborikawa** [comment]
本の詳細の実装後に行う。

**Comment by Hitoshi-Noborikawa** [comment]
# APIから呼び出すデータ
- 本の情報
- 本の貸し出し日
- 本の予約日

# 仕様（wikiから）
- 最長で2週間。
- 期間が重複してはいけない。
- 最大5冊

**Comment by Hitoshi-Noborikawa** [comment]
- [x] 期間が重複しては行けない
- [ ] 最大5冊
- [ ] 最長で2週間

**Comment by Hitoshi-Noborikawa** [comment]
時間がないので最長で2週間は後回しにする

**Comment by Hitoshi-Noborikawa** [comment]
別タスクにしました。クローズします
