### ISSUE TITLE
借りたい本を予約するページの作成

### ISSUE THREAD

**Issue by takanori-matsushita** [CODEBASE-Okinawa/codebase_books_nobotsun#8]
Notion
https://www.notion.so/codebase098/ce74e531a4424763b85e93638e0c7462?v=36964af226a44492a02f68f26e013a93&p=bbf99b4bdec743689e936fc1aef1a3ea&pm=s

- [x] デザインの作成
- [x] APIの実装
  - [x] 本の詳細を取得する
  - [x] 本の貸し出し日付と予約日付を合算したデータを取得する
  - [x] 予約日を登録する
- [x] 本を借りる際の画面の動きを実装
  - [x] 予約日が重複できないようにする
  - [ ] 2週間以上は予約できないようにする

**Comment by Hitoshi-Noborikawa** [comment]
本の詳細の実装後に行う。

**Comment by Hitoshi-Noborikawa** [comment]
時間がないので2週間以上は予約できないようにするのは後回しにする

**Comment by Hitoshi-Noborikawa** [comment]
別タスクにしました。クローズします
